SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

SHOW WARNINGS;
USE `emoodsic` ;

-- -----------------------------------------------------
-- Table `emoodsic`.`style`
-- -----------------------------------------------------
SELECT 'emoodsic.style' AS ' ';

TRUNCATE TABLE `emoodsic`.`style`;
INSERT INTO `emoodsic`.`style` (`idStyle`, `name`)
VALUES
	(1, 'acappella'),
	(2, 'alternative'),
	(3, 'ambient'),
	(4, 'bachata'),
	(5, 'ballad'),
	(6, 'baroque'),
	(7, 'basque rock'),
	(8, 'blues'),
	(9, 'bolero'),
	(10, 'break'),
	(11, 'cabaret'),
	(12, 'catalan music'),
	(13, 'celtic'),
	(14, 'children music'),
	(15, 'choral music'),
	(16, 'classical'),
	(17, 'country'),
	(18, 'cumbia'),
	(19, 'dance'),
	(20, 'deep house'),
	(21, 'drum and bass'),
	(22, 'dub reggae'),
	(23, 'dubstep'),
	(24, 'electro house'),
	(25, 'electronica'),
	(26, 'emo'),
	(27, 'fado'),
	(28, 'flamenco'),
	(29, 'folk'),
	(30, 'funk'),
	(31, 'galician folk'),
	(32, 'glitch hop'),
	(33, 'gospel'),
	(34, 'gothic'),
	(35, 'grunge'),
	(36, 'hard dance'),
	(37, 'hard rock'),
	(38, 'hardcore'),
	(39, 'hardtechno'),
	(40, 'heavy metal'),
	(41, 'heavy rock'),
	(42, 'hip hop'),
	(43, 'house'),
	(44, 'indie'),
	(45, 'instrumental'),
	(46, 'jazz'),
	(47, 'latin'),
	(48, 'lounge'),
	(49, 'mambo'),
	(50, 'medieval'),
	(51, 'merengue'),
	(52, 'metal'),
	(53, 'minimal'),
	(54, 'musical'),
	(55, 'nu disco'),
	(56, 'nu metal'),
	(57, 'old school'),
	(58, 'opera'),
	(59, 'pop'),
	(60, 'pop rock'),
	(61, 'progressive house'),
	(62, 'psychedelic trance'),
	(63, 'punk'),
	(64, 'r&b'),
	(65, 'rap'),
	(66, 'reggae'),
	(67, 'reggaeton'),
	(68, 'religious music'),
	(69, 'rock'),
	(70, 'rumba'),
	(71, 'salsa'),
	(72, 'samba'),
	(73, 'scratch'),
	(74, 'ska'),
	(75, 'soul'),
	(76, 'soundtrack'),
	(77, 'spanish alternative'),
	(78, 'spanish folk'),
	(79, 'spanish hard rock'),
	(80, 'spanish indie'),
	(81, 'spanish metal'),
	(82, 'spanish music'),
	(83, 'spanish pop'),
	(84, 'spanish pop rock'),
	(85, 'spanish punk'),
	(86, 'spanish rap'),
	(87, 'spanish rock'),
	(88, 'spanish ska'),
	(89, 'spiritual'),
	(90, 'swing'),
	(91, 'symphonic'),
	(92, 'tango'),
	(93, 'tech house'),
	(94, 'techno'),
	(95, 'trance');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
